# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mongo:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ./front/node_modules/
  - ./back/node_modules/

test_back:
  script:
   - cd ./back/
   - npm install
   - cd ../

test_ng: 
  script:
   - cd ./front/
   - npm install
   - ./node_modules/@angular/cli/bin/ng serve --single-run=true --browsers PhantomJS --watch=false
   - cd ../
