# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ./front/node_modules/
  - ./back/node_modules/

back_build:
  image: node:latest
  stage: build
  script:
    - cd ./back
    - npm install
    - nohup npm start &
    - echo "COUCOU"
    - cd ..

front_build:
  image: trion/ng-cli-karma
  stage: build
  script:
    - cd ./front
    - npm install 
    - ng build
    - cd ..

# test_back:
#   script:
#    - cd ./back/
#    - npm install
#    - npm build
#    - cd ../
# c'est de la ***   

front_test:
  image: trion/ng-cli-karma
  stage: test
  script:
    - cd ./front
    - npm install 
    - ng e2e --progress false --watch=false
    - ng test --watch=false
    - cd ..


